import { Inter } from "next/font/google";
import "./globals.css";
import BasedLayout from "./component/layout";
import Middleware from "./middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Middleware>
          <BasedLayout>{children}</BasedLayout>
        </Middleware>
      </body>
    </html>
  );
}
